# Generated by Django 4.2.1 on 2023-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='enquiry_table',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='enquiry_table',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='enquiry_table',
            old_name='name',
            new_name='Name',
        ),
    ]
